// pages/terms.js
import Head from 'next/head';
import Link from 'next/link';
import Header from '../components/Header'; // Assuming you want the header here too
import { Analytics } from "@vercel/analytics/next"
export default function TermsOfServicePage() {
  return (
    <>
      <Head>
        <title>Terms of Service - FusionSpace</title>
        <meta name="robots" content="noindex, nofollow" /> {/* Discourage search engines from indexing ToS */}
      </Head>
      <Header />

      <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-12 font-inter max-w-3xl">
        <div className="bg-white p-8 rounded-lg shadow-lg">
          <h1 className="text-3xl font-bold text-slate-800 mb-6">Terms of Service</h1>
          
          <p className="text-slate-600 mb-4">Last Updated: {new Date().toLocaleDateString()}</p>

          <p className="text-slate-700 mb-4">
            Welcome to FusionSpace! These Terms of Service (&quot;Terms&quot;) govern your use of the FusionSpace website,
            mobile application (if applicable), and services (collectively, the &quot;Service&quot;) provided by FusionSpace (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).
            By accessing or using our Service, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use our Service.
          </p>

          <h2 className="text-2xl font-semibold text-slate-700 mt-6 mb-3">1. Service Description</h2>
          <p className="text-slate-700 mb-4">
            FusionSpace provides a nutrition analysis tool that uses Artificial Intelligence (AI) to estimate caloric and macronutrient content
            of food items based on user-provided descriptions or images. The Service also allows users to set nutritional goals,
            track their intake, and receive insights based on their logged data.
          </p>

          <h2 className="text-2xl font-semibold text-slate-700 mt-6 mb-3">2. User Accounts</h2>
          <p className="text-slate-700 mb-4">
            To access certain features of the Service, you may be required to create an account. You are responsible for maintaining
            the confidentiality of your account information and for all activities that occur under your account. You agree to
            notify us immediately of any unauthorized use of your account.
          </p>
          
          <h2 className="text-2xl font-semibold text-slate-700 mt-6 mb-3">3. Use of the Service</h2>
          <p className="text-slate-700 mb-4">
            You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to use the Service:
          </p>
          <ul className="list-disc list-inside text-slate-700 mb-4 ml-4 space-y-1">
            <li>In any way that violates any applicable federal, state, local, or international law or regulation.</li>
            <li>To transmit, or procure the sending of, any advertising or promotional material without our prior written consent.</li>
            <li>To impersonate or attempt to impersonate FusionSpace, a FusionSpace employee, another user, or any other person or entity.</li>
            <li>To engage in any other conduct that restricts or inhibits anyone&apos;s use or enjoyment of the Service, or which, as determined by us, may harm FusionSpace or users of the Service or expose them to liability.</li>
          </ul>

          <h2 className="text-2xl font-semibold text-slate-700 mt-6 mb-3">4. AI Analysis and Nutritional Information</h2>
          <p className="text-slate-700 mb-1 font-semibold">Accuracy of Information:</p>
          <p className="text-slate-700 mb-4">
            The nutritional information provided by FusionSpace, including calorie counts, macronutrient breakdowns, and ingredient analysis,
            is generated by an AI model and is an <strong className="underline">ESTIMATE</strong> for informational purposes only. While we strive for accuracy,
            we cannot guarantee that the information provided will be completely accurate, complete, or up-to-date. Factors such as
            portion sizes, specific brands, preparation methods, and inherent variability in food items can affect actual nutritional content.
          </p>
          <p className="text-slate-700 mb-1 font-semibold">Medical Disclaimer:</p>
          <p className="text-red-600 font-semibold mb-2">
            FusionSpace IS NOT A MEDICAL DEVICE OR SERVICE. THE INFORMATION PROVIDED BY THE SERVICE IS NOT INTENDED TO DIAGNOSE, TREAT, CURE, OR PREVENT ANY DISEASE OR MEDICAL CONDITION.
            IT IS NOT A SUBSTITUTE FOR PROFESSIONAL MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT. ALWAYS SEEK THE ADVICE OF YOUR PHYSICIAN OR OTHER QUALIFIED HEALTH PROVIDER WITH ANY
            QUESTIONS YOU MAY HAVE REGARDING A MEDICAL CONDITION OR YOUR DIETARY NEEDS. NEVER DISREGARD PROFESSIONAL MEDICAL ADVICE OR DELAY IN SEEKING IT BECAUSE OF SOMETHING
            YOU HAVE READ OR ACCESSED THROUGH THE FusionSpace SERVICE. RELIANCE ON ANY INFORMATION PROVIDED BY FusionSpace IS SOLELY AT YOUR OWN RISK.
          </p>
          <p className="text-slate-700 mb-4">
            If you have any specific dietary restrictions, allergies, or medical conditions, consult with a healthcare professional or a registered dietitian before
            making any decisions based on information from FusionSpace.
          </p>

          <h2 className="text-2xl font-semibold text-slate-700 mt-6 mb-3">5. Intellectual Property</h2>
          <p className="text-slate-700 mb-4">
            The Service and its original content, features, and functionality are and will remain the exclusive property of FusionSpace
            and its licensors.
          </p>

          <h2 className="text-2xl font-semibold text-slate-700 mt-6 mb-3">6. Termination</h2>
          <p className="text-slate-700 mb-4">
            We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability,
            under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.
          </p>

          <h2 className="text-2xl font-semibold text-slate-700 mt-6 mb-3">7. Limitation of Liability</h2>
          <p className="text-slate-700 mb-4">
            In no event shall FusionSpace, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for
            any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data,
            use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
          </p>

          <h2 className="text-2xl font-semibold text-slate-700 mt-6 mb-3">8. Changes to Terms</h2>
          <p className="text-slate-700 mb-4">
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.
            By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms.
          </p>

          <h2 className="text-2xl font-semibold text-slate-700 mt-6 mb-3">9. Contact Us</h2>
          <p className="text-slate-700 mb-4">
            If you have any questions about these Terms, please contact us at [Your Contact Email or Method - Placeholder].
          </p>

          <div className="mt-8 border-t pt-6 text-center">
            <p className="text-sm text-slate-500">
              By using FusionSpace, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
            </p>
            <Link href="/" legacyBehavior>
              <a className="mt-4 inline-block text-green-600 hover:text-green-700 font-medium">
                &larr; Back to Home
              </a>
            </Link>
          </div>
          
          <p className="mt-10 text-xs text-center text-red-700 font-bold">
            DISCLAIMER: This Terms of Service is a template and for informational purposes only. It is NOT legal advice.
            You should consult with a legal professional to ensure your Terms of Service are appropriate for your specific
            situation and comply with all applicable laws and regulations.
          </p>

        </div>
      </main>
    </>
  );
}